### ISSUE TITLE
Update windows compilers

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/ace-feedstock#54]
Hey all

This feedstock is directly specifying `vs2017_win-64` as a dependency,
https://github.com/conda-forge/ace-feedstock/blob/846a48ca49a5f7a928b3a21dedacd0db87775eb7/recipe/meta.yaml#L17-L21

but should just rely on the `{{ compiler('c') }}` function to provide the correct compilers on windows. In particular, conda-forge has moved on to vs2019 as the default compiler a while ago already.

If you think you need vs2017, please let us know why (generally vs2019 and vs2022 should be fully compatible). If it's really necessary, please use the dedicated mechanism in `conda_build_config.yaml` for that, i.e.
```
c_compiler:     # [win]
  - vs2017      # [win]
cxx_compiler:   # [win]
  - vs2017      # [win]
```
as opposed to specifying it in `meta.yaml` directly

**Comment by traversaro** [comment]
Leftover from some kind of cargo cult of the past, let's fix this.

**Comment by traversaro** [comment]
> I think this is not just removing this flag, at the moment vs2019 or vs2022 is used as compiler you need to pass a different commandline option to mwc.pl, see
> 
> https://github.com/conda-forge/ace-feedstock/blob/202bf73abd9485e4cfe7c5155818f5b6304fe862/recipe/bld.bat#L18

Thanks for noticing this! Hopefully this will be fixed by https://github.com/conda-forge/ace-feedstock/pull/56 .
